# version: '3.9'

secrets:
  VERSIO_USERNAME:
    external: true
  VERSIO_PASSWORD:
    external: true

# configs:
# volumes:

networks:
  lan-develop:
    external: true
  wan-develop:
    external: true
  wan-platform:
    external: true
  lan-platform:
    external: true

services:

  traefik:
    image: "traefik:v3.3.6"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_PATH_CONFIG}/config.yml:/etc/traefik/traefik-config.yml
      - ${TRAEFIK_PATH_ETC}:/etc/traefik/dynamic
      - ${TRAEFIK_PATH_DATA}:/app/data
      - ${TRAEFIK_PATH_LOGS}:/app/logs
    networks:
      - wan-${WORKSPACE}
      - lan-${WORKSPACE}
    secrets:
      - VERSIO_USERNAME
      - VERSIO_PASSWORD
    environment:
      DOMAIN_DEV: ${DOMAIN_DEV}
      ENVIRONMENT: ${ENVIRONMENT}
      WORKSPACE: ${WORKSPACE}
      REALM_ID: ${REALM_ID}
      REALM_NAME: ${REALM_NAME}
      VERSIO_ENDPOINT: ${VERSIO_ENDPOINT}
      VERSIO_USERNAME_FILE: /run/secrets/VERSIO_USERNAME
      VERSIO_PASSWORD_FILE: /run/secrets/VERSIO_PASSWORD
    command: traefik --configFile=/etc/traefik/traefik-config.yml
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 120s
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager
          - node.labels.manager==true
      restart_policy:
        condition: on-failure
        delay: 10s
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 30s
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        # Basic Authentication
        - traefik.http.middlewares.basic-auth.basicauth.users=root:$$apr1$$QWdnNA46$$ERyQkE85h.jRxDlkEFTcU.
        # Traefik dashboard
        - traefik.http.services.traefik.loadbalancer.server.scheme=http
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_DEV}`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.entrypoints=websecure
        - traefik.http.routers.traefik.tls.certresolver=${TRAEFIK_TLS_HTTP}
        - traefik.http.routers.traefik.middlewares=basic-auth
